// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
/*
 * @Author: yanxlg
 * @Date: 2023-04-26 13:58:45
 * @LastEditors: yanxlg
 * @LastEditTime: 2023-04-28 00:08:22
 * @Description: 环境变量注入
 *
 * Copyright (c) 2023 by yanxlg, All Rights Reserved.
 */

const sentry_environment = "local";

const InjectEnvs = { sentry_environment };

export { InjectEnvs };
