// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { init } from "@yh/yh-sauron";
import { InjectEnvs } from 'umi';
//import * as RuntimeConfig from '/Users/yanxianliang/Desktop/yonghui/umi-middle/src/app.tsx';

//if(RuntimeConfig && RuntimeConfig.sauron){

//}
//const sauronConfig = RuntimeConfig.sauron(); // 注册自定义埋点
init({
  app_name: "test",
  project_name: "yh_life",
  env: InjectEnvs?.sauron_environment || 'dev',
  debug: true,
  useWebPerformance: false,
  webPerformanceRouteList: ["/"],
  useListenException: {},
  useListenAndSendSlowRequest: false,
  useListenPageView: true,
  useListenRequestDuration: true,
  useListenInterfaceException: {
  "rules": [
    {
      "pathRule": "*",
      "successCodes": [
        "200000"
      ]
    }
  ]
},
  useAutoListenSendBlock: false,
  useAutoListenAndSendClick: false
});
