// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { ClickToComponent } from 'click-to-react-component';
import React from 'react';
export function rootContainer(container, opts) {
return React.createElement(
  (props) => {
    return (
      <>
        <ClickToComponent editor="webstorm"/>
        {props.children}
      </>
    );
  },
  opts,
  container,
);
}
