// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import Container from './Container';

export function dataflowProvider(container: React.ReactNode, clientProps: any) {    
  return (
    <Container>{container}</Container>
  );
}
