// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import type { RunTimeWatermarkLayoutConfig } from './types.d';
export interface IRuntimeConfig {
  watermark?: RunTimeWatermarkLayoutConfig
}
