// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
type InitDataType = any;
export type WatermarkConfig = {
  gapX?: number;
  /** 水印之间的垂直间距 */
  gapY?: number;
  /** 追加的水印元素的z-index */
  zIndex?: number;
  /** 水印的宽度 */
  width?: number;
  /** 水印的高度 */
  height?: number;
  /** 水印在canvas 画布上绘制的垂直偏移量，正常情况下，水印绘制在中间位置, 即 offsetTop = gapY / 2 */
  offsetTop?: number; // 水印图片距离绘制 canvas 单元的顶部距离
  /** 水印在canvas 画布上绘制的水平偏移量, 正常情况下，水印绘制在中间位置, 即 offsetTop = gapX / 2 */
  offsetLeft?: number;
  /** 水印绘制时，旋转的角度，单位 ° */
  rotate?: number;
  /** ClassName 前缀 */
  prefixCls?: string;
  /** 高清印图片源, 为了高清屏幕显示，建议使用 2倍或3倍图，优先使用图片渲染水印。 */
  image?: string;
  /** 水印文字内容 */
  content?: string | string[];
  /** 文字颜色 */
  fontColor?: string;
  /** 文字样式 */
  fontStyle?: "none" | "normal" | "italic" | "oblique";
  /** 文字族 */
  fontFamily?: string;
  /** 文字粗细 */
  fontWeight?: "normal" | "light" | "weight" | number;
  /** 文字大小 */
  fontSize?: number | string;
};
export type RunTimeWatermarkLayoutConfig = (initData: InitDataType) => WatermarkConfig;
