// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import * as Sentry from "@sentry/react";
import { InjectEnvs } from 'umi';

Sentry.init({
  dsn: "https://5666cb429d8b47b79f4c44de90c029fb@sentry.yonghuivip.com/213",
  integrations: [
    new Sentry.BrowserTracing(),
    // new Sentry.Replay() // 行为轨迹回放。
  ],
  tracesSampleRate: 1.0,
  replaysSessionSampleRate: 0.1,
  replaysOnErrorSampleRate: 1.0,
  environment: InjectEnvs?.sentry_environment??"local", // inject from environment
  debug: true,
  disabled: true,
  ignoreErrors: ["promise rejection","chrome.loadTimes() is deprecated","Request aborted","ResizeObserver","Failed to fetch","RequestError: timeout"],
  release: "local",
});
